//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leviathan.Model.CharacterRelated.SkillRelated.Skills.Warrior {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class WarriorResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WarriorResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leviathan.Model.CharacterRelated.SkillRelated.Skills.Warrior.WarriorResources", typeof(WarriorResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Skill1_Cooldown {
            get {
                return ResourceManager.GetString("Skill1_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Skill1_Duration {
            get {
                return ResourceManager.GetString("Skill1_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warrior_heroic_slash.
        /// </summary>
        internal static string Skill1_ImageName {
            get {
                return ResourceManager.GetString("Skill1_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Skill1_LevelRequired {
            get {
                return ResourceManager.GetString("Skill1_LevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Skill1_ManaCost {
            get {
                return ResourceManager.GetString("Skill1_ManaCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic Slash.
        /// </summary>
        internal static string Skill1_Name {
            get {
                return ResourceManager.GetString("Skill1_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Skill1_PlusAttack {
            get {
                return ResourceManager.GetString("Skill1_PlusAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Skill1_Range {
            get {
                return ResourceManager.GetString("Skill1_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heroic Slash\r\nASD\r\nDamage: 5\r\nMana Cost: 0\r\nCooldown: 2 turns.
        /// </summary>
        internal static string Skill1_ToolTip {
            get {
                return ResourceManager.GetString("Skill1_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A;B;C.
        /// </summary>
        internal static string Skill1_UseMessage {
            get {
                return ResourceManager.GetString("Skill1_UseMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Skill2_Cooldown {
            get {
                return ResourceManager.GetString("Skill2_Cooldown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Skill2_Duration {
            get {
                return ResourceManager.GetString("Skill2_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to warrior_shild_block.
        /// </summary>
        internal static string Skill2_ImageName {
            get {
                return ResourceManager.GetString("Skill2_ImageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Skill2_LevelRequired {
            get {
                return ResourceManager.GetString("Skill2_LevelRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Skill2_ManaCost {
            get {
                return ResourceManager.GetString("Skill2_ManaCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Block.
        /// </summary>
        internal static string Skill2_Name {
            get {
                return ResourceManager.GetString("Skill2_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -2.
        /// </summary>
        internal static string Skill2_PlusAttack {
            get {
                return ResourceManager.GetString("Skill2_PlusAttack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Skill2_PlusDefense {
            get {
                return ResourceManager.GetString("Skill2_PlusDefense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000.
        /// </summary>
        internal static string Skill2_Range {
            get {
                return ResourceManager.GetString("Skill2_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shield Block\r\nADS\r\nDefense: 5\r\nDamage: -2\r\nMana Cost: 0\r\nCooldown: 5 turns.
        /// </summary>
        internal static string Skill2_ToolTip {
            get {
                return ResourceManager.GetString("Skill2_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D;E;F.
        /// </summary>
        internal static string Skill2_UseMessage {
            get {
                return ResourceManager.GetString("Skill2_UseMessage", resourceCulture);
            }
        }
    }
}
