//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Leviathan.Model.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Leviathan.Model.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Druid_Attack {
            get {
                return ResourceManager.GetString("Druid_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Druid_Defense {
            get {
                return ResourceManager.GetString("Druid_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Druid_Health {
            get {
                return ResourceManager.GetString("Druid_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Druid_Mana {
            get {
                return ResourceManager.GetString("Druid_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Druid_Speed {
            get {
                return ResourceManager.GetString("Druid_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Druid_Start_Attack_High {
            get {
                return ResourceManager.GetString("Druid_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Druid_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Druid_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Druid_Start_Defense_High {
            get {
                return ResourceManager.GetString("Druid_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Druid_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Druid_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Druid_Start_Health {
            get {
                return ResourceManager.GetString("Druid_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Druid_Start_Mana {
            get {
                return ResourceManager.GetString("Druid_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Druid_Start_Speed {
            get {
                return ResourceManager.GetString("Druid_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Dwarf_Attack {
            get {
                return ResourceManager.GetString("Dwarf_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Dwarf_Defense {
            get {
                return ResourceManager.GetString("Dwarf_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Dwarf_Health {
            get {
                return ResourceManager.GetString("Dwarf_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Dwarf_Mana {
            get {
                return ResourceManager.GetString("Dwarf_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Dwarf_Speed {
            get {
                return ResourceManager.GetString("Dwarf_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Dwarf_Start_Attack_High {
            get {
                return ResourceManager.GetString("Dwarf_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Dwarf_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Dwarf_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Dwarf_Start_Defense_High {
            get {
                return ResourceManager.GetString("Dwarf_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Dwarf_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Dwarf_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 12.
        /// </summary>
        internal static string Dwarf_Start_Health {
            get {
                return ResourceManager.GetString("Dwarf_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Dwarf_Start_Mana {
            get {
                return ResourceManager.GetString("Dwarf_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Dwarf_Start_Speed {
            get {
                return ResourceManager.GetString("Dwarf_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Elf_Attack {
            get {
                return ResourceManager.GetString("Elf_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Elf_Defense {
            get {
                return ResourceManager.GetString("Elf_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Elf_Health {
            get {
                return ResourceManager.GetString("Elf_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Elf_Mana {
            get {
                return ResourceManager.GetString("Elf_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Elf_Speed {
            get {
                return ResourceManager.GetString("Elf_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Elf_Start_Attack_High {
            get {
                return ResourceManager.GetString("Elf_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Elf_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Elf_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Elf_Start_Defense_High {
            get {
                return ResourceManager.GetString("Elf_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Elf_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Elf_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Elf_Start_Health {
            get {
                return ResourceManager.GetString("Elf_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Elf_Start_Mana {
            get {
                return ResourceManager.GetString("Elf_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string Elf_Start_Speed {
            get {
                return ResourceManager.GetString("Elf_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Human_Attack {
            get {
                return ResourceManager.GetString("Human_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Human_Defense {
            get {
                return ResourceManager.GetString("Human_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Human_Health {
            get {
                return ResourceManager.GetString("Human_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Human_Mana {
            get {
                return ResourceManager.GetString("Human_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Human_Speed {
            get {
                return ResourceManager.GetString("Human_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Human_Start_Attack_High {
            get {
                return ResourceManager.GetString("Human_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Human_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Human_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Human_Start_Defense_High {
            get {
                return ResourceManager.GetString("Human_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Human_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Human_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Human_Start_Health {
            get {
                return ResourceManager.GetString("Human_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Human_Start_Mana {
            get {
                return ResourceManager.GetString("Human_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Human_Start_Speed {
            get {
                return ResourceManager.GetString("Human_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Mage_Attack {
            get {
                return ResourceManager.GetString("Mage_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Mage_Defense {
            get {
                return ResourceManager.GetString("Mage_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Mage_Health {
            get {
                return ResourceManager.GetString("Mage_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Mage_Mana {
            get {
                return ResourceManager.GetString("Mage_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Mage_Speed {
            get {
                return ResourceManager.GetString("Mage_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Mage_Start_Attack_High {
            get {
                return ResourceManager.GetString("Mage_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Mage_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Mage_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Mage_Start_Defense_High {
            get {
                return ResourceManager.GetString("Mage_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Mage_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Mage_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Mage_Start_Health {
            get {
                return ResourceManager.GetString("Mage_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string Mage_Start_Mana {
            get {
                return ResourceManager.GetString("Mage_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Mage_Start_Speed {
            get {
                return ResourceManager.GetString("Mage_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Orc_Attack {
            get {
                return ResourceManager.GetString("Orc_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Orc_Defense {
            get {
                return ResourceManager.GetString("Orc_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Orc_Health {
            get {
                return ResourceManager.GetString("Orc_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Orc_Mana {
            get {
                return ResourceManager.GetString("Orc_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Orc_Speed {
            get {
                return ResourceManager.GetString("Orc_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Orc_Start_Attack_High {
            get {
                return ResourceManager.GetString("Orc_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Orc_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Orc_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Orc_Start_Defense_High {
            get {
                return ResourceManager.GetString("Orc_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Orc_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Orc_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 15.
        /// </summary>
        internal static string Orc_Start_Health {
            get {
                return ResourceManager.GetString("Orc_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Orc_Start_Mana {
            get {
                return ResourceManager.GetString("Orc_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Orc_Start_Speed {
            get {
                return ResourceManager.GetString("Orc_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Ranger_Attack {
            get {
                return ResourceManager.GetString("Ranger_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Ranger_Defense {
            get {
                return ResourceManager.GetString("Ranger_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Ranger_Health {
            get {
                return ResourceManager.GetString("Ranger_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Ranger_Mana {
            get {
                return ResourceManager.GetString("Ranger_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Ranger_Speed {
            get {
                return ResourceManager.GetString("Ranger_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Ranger_Start_Attack_High {
            get {
                return ResourceManager.GetString("Ranger_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Ranger_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Ranger_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Ranger_Start_Defense_High {
            get {
                return ResourceManager.GetString("Ranger_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Ranger_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Ranger_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Ranger_Start_Health {
            get {
                return ResourceManager.GetString("Ranger_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Ranger_Start_Mana {
            get {
                return ResourceManager.GetString("Ranger_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Ranger_Start_Speed {
            get {
                return ResourceManager.GetString("Ranger_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Rogue_Attack {
            get {
                return ResourceManager.GetString("Rogue_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Rogue_Defense {
            get {
                return ResourceManager.GetString("Rogue_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Rogue_Health {
            get {
                return ResourceManager.GetString("Rogue_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Rogue_Mana {
            get {
                return ResourceManager.GetString("Rogue_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Rogue_Speed {
            get {
                return ResourceManager.GetString("Rogue_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Rogue_Start_Attack_High {
            get {
                return ResourceManager.GetString("Rogue_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Rogue_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Rogue_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Rogue_Start_Defense_High {
            get {
                return ResourceManager.GetString("Rogue_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Rogue_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Rogue_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Rogue_Start_Health {
            get {
                return ResourceManager.GetString("Rogue_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Rogue_Start_Mana {
            get {
                return ResourceManager.GetString("Rogue_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Rogue_Start_Speed {
            get {
                return ResourceManager.GetString("Rogue_Start_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Warrior_Attack {
            get {
                return ResourceManager.GetString("Warrior_Attack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Warrior_Defense {
            get {
                return ResourceManager.GetString("Warrior_Defense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Warrior_Health {
            get {
                return ResourceManager.GetString("Warrior_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Warrior_Mana {
            get {
                return ResourceManager.GetString("Warrior_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Warrior_Speed {
            get {
                return ResourceManager.GetString("Warrior_Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Warrior_Start_Attack_High {
            get {
                return ResourceManager.GetString("Warrior_Start_Attack_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Warrior_Start_Attack_Low {
            get {
                return ResourceManager.GetString("Warrior_Start_Attack_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Warrior_Start_Defense_High {
            get {
                return ResourceManager.GetString("Warrior_Start_Defense_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Warrior_Start_Defense_Low {
            get {
                return ResourceManager.GetString("Warrior_Start_Defense_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Warrior_Start_Health {
            get {
                return ResourceManager.GetString("Warrior_Start_Health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        internal static string Warrior_Start_Mana {
            get {
                return ResourceManager.GetString("Warrior_Start_Mana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Warrior_Start_Speed {
            get {
                return ResourceManager.GetString("Warrior_Start_Speed", resourceCulture);
            }
        }
    }
}
